apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: golfleaguemaster-com-tls
spec:
  secretName: golfleaguemaster-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: golfleaguemaster.com
  dnsNames:
    - golfleaguemaster.com
    - www.golfleaguemaster.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - golfleaguemaster.com
        - www.golfleaguemaster.com
